Update WelcomeConverter.java
Fix startup when using the following command from the readme
2- Build
mvn clean install
3- Run
java -jar target/joinfaces-example-5.4.x.jar

java.lang.NullPointerException: Cannot invoke "org.omnifaces.cdi.converter.ConverterManager.createConverter(jakarta.faces.application.Application, java.lang.Class)" because "this.converterManager" is null ...